
-- Generated by ORDS REST Data Services 23.1.2.r1151944
-- Schema: WKSP_WS1  Date: Thu May 04 09:44:22 2023 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_WS1',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'apidemo',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'hr/v1/',
      p_base_path      => '/hr/v1/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hr/v1/',
      p_pattern        => 'employees/:id?',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hr/v1/',
      p_pattern        => 'employees/:id?',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT e.employee_id,
       e.first_name,
       e.last_name,
       e.email,
       e.phone_number,
       e.hire_date,
       e.job_id,
       e.salary,
       e.commission_pct,
       e.manager_id,
       e.department_id
FROM oehr_employees e
WHERE e.employee_id = :id or :id is null');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hr/v1/',
      p_pattern        => 'employees/:id?',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
   HR_API_V1.UPDATE_EMP(
      P_EMPLOYEE_ID    => :id,
      P_FIRST_NAME     => :first_name,
      P_LAST_NAME      => :last_name,
      P_EMAIL          => :email,
      P_PHONE_NUMBER   => :phone,
      P_HIRE_DATE      => :hire_date,
      P_JOB_ID         => :job_id,
      P_SALARY         => :salary,
      P_COMMISSION_PCT => :comm,
      P_MANAGER_ID     => :manager_id,
      P_DEPARTMENT_ID  => :department_id,
      P_RES_LOC        => :res_location,
      P_STATUS_CD      => :status,
      P_STATUS_MSG     => :status_msg  
   );
   
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'PUT',
      p_name               => '$self',
      p_bind_variable_name => 'res_location',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'PUT',
      p_name               => 'status_msg',
      p_bind_variable_name => 'status_msg',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hr/v1/',
      p_pattern        => 'employees/:id?',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
   HR_API_V1.DELETE_EMP(
      P_EMPLOYEE_ID    => :id,
      P_STATUS_CD      => :status,
      P_STATUS_MSG     => :status_msg  
   );
   
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'DELETE',
      p_name               => 'status_msg',
      p_bind_variable_name => 'status_msg',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'DELETE',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hr/v1/',
      p_pattern        => 'employees/:id?',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
   HR_API_V1.CREATE_EMP(
      P_EMPLOYEE_ID    => :employee_id,
      P_FIRST_NAME     => :first_name,
      P_LAST_NAME      => :last_name,
      P_EMAIL          => :email,
      P_PHONE_NUMBER   => :phone,
      P_HIRE_DATE      => :hire_date,
      P_JOB_ID         => :job_id,
      P_SALARY         => :salary,
      P_COMMISSION_PCT => :comm,
      P_MANAGER_ID     => :manager_id,
      P_DEPARTMENT_ID  => :department_id,
      P_RES_LOC        => :res_location,
      P_STATUS_CD      => :status,
      P_STATUS_MSG     => :status_msg  
   );
   
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'POST',
      p_name               => '$self',
      p_bind_variable_name => 'res_location',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'POST',
      p_name               => 'status_msg',
      p_bind_variable_name => 'status_msg',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'hr/v1/',
      p_pattern            => 'employees/:id?',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

    
        
COMMIT;

END;